---
title: "NHL standings investigation"
author: "Andrew Pike"
date: "11/17/2021"
output: html_document
---

## Load Libraries
```{r load_libraries, echo = FALSE}

library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(reshape2)

print(.packages())

```

## Load Tables

All data was sourced from Hockey-Reference.com

Example -> https://www.hockey-reference.com/leagues/NHL_2021_standings.html

```{r load_tables, echo = FALSE, warning = FALSE, message = FALSE}
standings_2020_21 <- read_csv("data/2020_21_standings.csv")
standings_2019_20 <- read_csv("data/2019_20_standings.csv")
standings_2018_19 <- read_csv("data/2018_19_standings.csv")
standings_2017_18 <- read_csv("data/2017_18_standings.csv")
standings_2016_17 <- read_csv("data/2016_17_standings.csv")
standings_2015_16 <- read_csv("data/2015_16_standings.csv")
standings_2014_15 <- read_csv("data/2014_15_standings.csv")
standings_2013_14 <- read_csv("data/2013_14_standings.csv")
standings_2012_13 <- read_csv("data/2012_13_standings.csv")
standings_2011_12 <- read_csv("data/2011_12_standings.csv")
standings_2010_11 <- read_csv("data/2010_11_standings.csv")
standings_2009_10 <- read_csv("data/2009_10_standings.csv")
standings_2008_09 <- read_csv("data/2008_09_standings.csv")
standings_2007_08 <- read_csv("data/2007_08_standings.csv")
standings_2006_07 <- read_csv("data/2006_07_standings.csv")
standings_2005_06 <- read_csv("data/2005_06_standings.csv")

list_standings <- list(
    standings_2020_21,
    standings_2019_20,
    standings_2018_19,
    standings_2017_18,
    standings_2016_17,
    standings_2015_16,
    standings_2014_15,
    standings_2013_14,
    standings_2012_13,
    standings_2011_12,
    standings_2010_11,
    standings_2009_10,
    standings_2008_09,
    standings_2007_08,
    standings_2006_07,
    standings_2005_06
)

standings_merged <- bind_rows(list_standings, .id = "column_label")
```


## Clean Standings Table
```{r clean_data, echo = FALSE, warning = FALSE, message = FALSE}
clean_table <- function(df_in) {
    df_out <- df_in %>%
        separate(Overall, c("wins", "losses", "ot_losses"), "-") %>%
        separate(Shootout, c("so_wins", "so_losses"), "-") %>%
        separate(Overtime, c("ot_wins", "ot_only_losses"), "-") %>%
        mutate(
            ot_wins = as.numeric(ot_wins) + as.numeric(so_wins),
            wins = as.numeric(wins),
            losses = as.numeric(losses),
            ot_losses = as.numeric(ot_losses),
            year = case_when(
                column_label == 1 ~ "20_21",
                column_label == 2 ~ "19_20",
                column_label == 3 ~ "18_19",
                column_label == 4 ~ "17_18",
                column_label == 5 ~ "16_17",
                column_label == 6 ~ "15_16",
                column_label == 7 ~ "14_15",
                column_label == 8 ~ "13_14",
                column_label == 9 ~ "12_13",
                column_label == 10 ~ "11_12",
                column_label == 11 ~ "10_11",
                column_label == 12 ~ "09_10",
                column_label == 13 ~ "08_09",
                column_label == 14 ~ "07_08",
                column_label == 15 ~ "06_07",
                column_label == 16 ~ "05_06"
            )
        ) %>%
        select(
            Rk,
            Team,
            wins,
            losses,
            ot_losses,
            ot_wins,
            year
        )
    return(df_out)
}

clean_standings_merged <- clean_table(standings_merged)
```

## Clean division table
```{r clean_division_table, echo = FALSE, warning = FALSE, message = FALSE}
#quick division table clean up

div_conf <- read_csv("data/conference_division_alignment.csv")

div_conf_long <- div_conf %>%
    pivot_longer(
        !Team,
        names_to = "div_conf",
        values_to = "group"
    )

div_conf_split <- colsplit(
    div_conf_long$div_conf,
    "_",
    c("group_level", "year")
)

div_conf_long <- cbind(div_conf_long, div_conf_split)

```


## Apply points schemas

```{r, echo = FALSE, warning = FALSE, message = FALSE}
apply_point_system <- function(df_in) {
    df_out <- df_in %>%
        mutate(
            points_2 = (2 * wins) + (1 * ot_losses),
            points_3 = (3 * wins) + (2 * ot_wins) + (1 * ot_losses),
            points_win_loss = wins
        )
    return(df_out)
}

merged_standings_w_points <- apply_point_system(clean_standings_merged)

merged_standings_points_div <- merge(
    merged_standings_w_points,
    div_conf_long,
    by = c("Team", "year"),
    all = TRUE)

```

## Build Playoff Spot Functions



```{r, echo = FALSE, warning = FALSE, message = FALSE}

#2020 - 2021 playoff teams were top 4 in each division.

set_2020_2021_playoff_teams <- function(df_in) {

    df_out <- df_in %>%
        drop_na() %>%
        filter(
            year == "20_21",
            group_level == "div"
        ) %>%
        group_by(group) %>%
        mutate(div_order_p2 = order(order(points_2, decreasing = TRUE))) %>%
        ungroup()

}

test <- set_2020_2021_playoff_teams(merged_standings_points_div)
```